server:
  port: 80
#  error:
#    whitelabel:
#      enabled: false    #禁用当前springboot提供的错误页面默认配置
spring:
  datasource:
    url: jdbc:mysql://39.96.59.235/weixin_shopping
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Xiaoluo301817.
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false


mybatis:
  config-location: classpath:config/mybatis-cfg.xml
  mapper-locations: classpath:config/mapper/**.xml



